## 1. Imputer 1

In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]

In [3]:
imp_mean = SimpleImputer()
imp_mean.fit(train_data)
print(imp_mean.statistics_, "\n")
np.all(imp_mean.statistics_ == np.nanmean(train_data, axis=0))

[ 4. 13.  6.] 



np.True_

In [4]:
print(imp_mean.transform(train_data), "\n")
imp_mean.transform(test_data)

[[ 7.  6.  5.]
 [ 4. 13.  5.]
 [ 1. 20.  8.]] 



array([[ 4.,  1.,  2.],
       [ 7., 13.,  9.],
       [ 4.,  2.,  4.]])