## 1. Imputer 1

In [1]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [2]:
train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]

In [3]:
imp_mean = SimpleImputer()
imp_mean.fit(train_data)
print(imp_mean.statistics_, "\n")
np.all(imp_mean.statistics_ == np.nanmean(train_data, axis=0))

[ 4. 13.  6.] 



np.True_

In [4]:
print(imp_mean.transform(train_data), "\n")
imp_mean.transform(test_data)

[[ 7.  6.  5.]
 [ 4. 13.  5.]
 [ 1. 20.  8.]] 



array([[ 4.,  1.,  2.],
       [ 7., 13.,  9.],
       [ 4.,  2.,  4.]])

## 2. Scaler

In [5]:
X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])
X_test = np.array([[ 2., -1.,  1.],
                     [ 3.,  3.,  -1.],
                     [ 1.,  1., 1.]])

In [6]:
scaler = StandardScaler()
X_train_transform = scaler.fit_transform(X_train)
X_train_transform

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
np.mean(X_train_transform, axis=0)

array([0., 0., 0.])

In [8]:
np.std(X_train_transform, axis=0)

array([1., 1., 1.])

In [9]:
scaler.transform(X_test)

array([[ 1.22474487, -1.22474487,  0.53452248],
       [ 2.44948974,  3.67423461, -1.06904497],
       [ 0.        ,  1.22474487,  0.53452248]])

## 3. One hot encoder

In [11]:
X_train = [['Python'], ['Java'], ['Java'], ['C++']]
X_test = [['Python'], ['Java'], ['C'], ['C++']]

In [12]:
enc = OneHotEncoder(handle_unknown="ignore")
enc.fit(X_train)
X_train_transform = enc.transform(X_train)
pd.DataFrame(data=X_train_transform.toarray(), columns=enc.categories_[0])

C++  Java  Python
0  0.0   0.0     1.0
1  0.0   1.0     0.0
2  0.0   1.0     0.0
3  1.0   0.0     0.0

In [13]:
X_test_transform = enc.transform(X_test)
pd.DataFrame(data=X_test_transform.toarray(), columns=enc.categories_)

C++ Java Python
0  0.0  0.0    1.0
1  0.0  1.0    0.0
2  0.0  0.0    0.0
3  1.0  0.0    0.0